
var en6 = ["english/ɪŋɡlɪʃ/a certain language","apple/ˈæp(ə)l/a kind of fruit",
"run/rʌn/a way for exercise",
"blue/blu/ one of the colors",
"apple/ˈæp(ə)l/the fleshy, usually rounded red, yellow, or green edible pome fruit of a usually cultivated tree (genus Malus) of the rose family",
"run/rʌn/to go faster than a walk",
"blue/blu/ of the color whose hue is that of the clear sky : of the color blue ",
"foot/ˈfu̇t/the terminal part of the vertebrate leg upon which an individual stands",
"head/hed/ the upper or anterior division of the animal body that contains the brain, the chief sense organs, and the mouth",
"hair/ˈher/ a slender threadlike outgrowth of the epidermis of an animal",
"blue/blu/ one of the colors",
"nose/ˈnōz/the part of the face that bears the nostrils and covers the anterior part of the nasal cavity",
"mouth/ˈmau̇th/the natural opening through which food passes into the body of an animal and which in vertebrates is typically bounded externally by the lips and internally by the pharynx and encloses the tongue, gums, and teeth",
"eye/ˈī/a specialized light-sensitive sensory structure of animals that in nearly all vertebrates, most arthropods, and some mollusks is the image-forming organ of sight",
"ear/ˈir/the characteristic vertebrate organ of hearing and equilibrium consisting in the typical mammal of a sound-collecting outer ear separated by the tympanic membrane from a sound-transmitting middle ear that in turn is separated from a sensory inner ear by membranous fenestrae",
"arm/ˈärm/a human upper limb",
" hand/ˈhand/the terminal part of the vertebrate forelimb when modified (as in humans) as a grasping organ : the body part at the end of the arm of a human, ape, or monkey",
"finger/ˈfiŋ-gər/to go faster than a walk",
"leg/ˈleg/a limb of an animal used especially for supporting the body and for walking: such as",
"tail/ˈtāl/ the rear end or a process or prolongation of the rear end of the body of an animal",
"red/ˈred/of the color red",
"pen/pen/an implement for writing or drawing with ink or a similar fluid",
"pencil/rʌn/to paint, draw, write, or mark with a pencil",
"ruler/rʌn/a worker or a machine that rules paper",
"one/ˈwən / being a single unit or thing ",
"two/ˈtü / being one more than one in number ",
"three/ˈthrē / a number that is one more than 2 ",
"four/ˈfȯr /  a number that is one more than three ",
"five /ˈfīv / a number that is one more than four ",
"six/ˈsiks / a number that is one more than five ",
"seven/ˈse-vən / a number that is one more than six ",
"eight/ˈāt / a number that is one more than seven ",
"nine/ˈnīn /a number that is one more than eight ",
"ten/ˈten / a number that is one more than nine ",
"big/ˈbig / large or great in dimensions, bulk, or extent",
"small/ˈsmȯl / having comparatively little size or slight dimensions ",
"tall/ˈtȯl / high in stature ",
"long/ˈlȯŋ / extending for a considerable distance ",
"short/ˈshȯrt / having little length",
"young/ˈyəŋ / being in the first or an early stage of life, growth, or development ",
"old/ˈōld / dating from the remote past ",
"strong/ˈstrȯŋ / having or marked by great physical power ",
"thin/ˈthin / having little extent from one surface to its opposite ",
"active/ˈak-tiv / characterized by action rather than by contemplation or speculation ",
"quiet/ˈkwī-ət / free from noise or uproar ",
"nice/ˈnīs/ polite, kind ",
"kind/ˈkīnd /a group united by common traits or interests ",
"strict/ˈstrikt / stringent in requirement or control ",
"smart/ˈsmärt / having or showing a high degree of mental ability ",
"funny/ˈfə-nē /affording light mirth and laughter ",
"tasty/ˈtā-stē / having a marked and appetizing flavor ",
"sweet/ˈswēt /  being, inducing, or marked by the one of the five basic taste sensations that is usually pleasing to the taste and typically induced by sugars (as sucrose or glucose) ",
"salty/ˈsȯl-tē / of, seasoned with, or containing salt ",
"sour/ˈsau̇(-ə)r / being, inducing, or marked by the one of the five basic taste sensations that is produced chiefly by acids and is characteristic of lemon juice ",
"fresh/ˈfresh / having its original qualities unimpaired ",
"favorite/ˈfā-v(ə-)rət/one that is treated or regarded with special favor or liking ",
"clean/ˈklēn / free from dirt or pollution ",
"tired/ˈtī(-ə)rd / drained of strength and energy ",
"excited/ ik-ˈsī-təd / characterized by a heightened state of energy, enthusiasm, eagerness ",
"angry/ˈaŋ-grē/ feeling or showing anger ",
"happy/ˈha-pē/ favored by luck or fortune ",
"bored/ˈbȯrd / filled with or characterized by boredom ",
"sad/ˈsad / affected with or expressive of grief or unhappiness ",
"good/ˈgu̇d / of a favorable character or tendency ",
"fine/ˈfīn / all right",
"great/ˈgrāt / notably large in size ",
"heavy/ˈhe-vē/ having great weight ",
"new/ˈnü/ having recently come into existence ",
"fat/ˈfat / notable for having an unusual amount of fat ",
"right/ˈrīt / righteous, upright",
"hungry/ˈhəŋ-grē/ feeling an uneasy or painful sensation from lack of food ",
"cute/ˈkyüt / clever or shrewd often in an underhanded manner ",
"little/ˈli-tᵊl / not big ",
"lovely/ˈləv-lē/ delightful for beauty, harmony, or grace ",
"beautiful/ˈbyü-ti-fəl / having qualities of beauty ",
"colorful/ˈkə-lər-fəl / having striking colors ",
"pretty/ˈpri-tē/ artful, clever ",
"cheap/ˈchēp / charging or obtainable at a low price ",
"expensive/ ik-ˈspen(t)-siv / involving high cost or sacrifice ",
"juicy/ˈjü-sē/ having much juice ",
"tender/ˈten-dər / marked by, responding to, or expressing the softer emotions ",
"healthy/ˈhel-thē/ enjoying good health ",
"ill/ˈil /  not in good health ",
"helpful/ˈhelp-fəl / of service or assistance ",
"high/ˈhī/ rising or extending upward a great distance  ",
"easy/ˈē-zē/ causing or involving little difficulty or discomfort ",
"proud/ˈprau̇d / feeling or showing pride ",
"sick/ˈsik / affected with disease or ill health ",
"better/ˈbe-tər / greater than half ",
"in/ˈin/ used as a function word to indicate inclusion, location, or position within limits ",
"on/ˈȯn/ used as a function word to indicate position in contact with and supported by the top surface of ",
"under/ˈən-dər / in or into a position below or beneath something ",
"near/ˈnir / at, within, or to a short distance or time ",
"behind/ bi-ˈhīnd / in the place or situation that is being or has been departed from ",
"over/ˈō-vər /across a barrier or intervening space",
"I/ˈī/ someone aware of possessing a personal individuality ",
"we/ˈwē/  I and the rest of a group that includes me : you and I : you and I and another or others : I and another or others not including you —used as pronoun of the first person plural ",
"you/ˈyü / the one or ones being addressed —used as the pronoun of the second person singular or plural in any grammatical relation except that of a possessive ",
"he/ˈhē / that male one who is neither speaker nor hearer ",
"she/ˈshē / that female one who is neither speaker nor hearer "]